### ISSUE TITLE
Fix: rewrite `ContactCard.js` link row using react component 

### ISSUE THREAD

**Issue by sarkartanmay393** [sarkartanmay393/Portfolio-V2#1]
Write a function that takes some params and return a react component. 

<img width="1440" alt="Screenshot 2023-01-27 at 7 48 47 PM" src="https://user-images.githubusercontent.com/84321236/215108819-920877bc-3153-4ab0-8f9b-194200fe1761.png" />

**Comment by abhijithp05** [comment]
@sarkartanmay393 Assign it to me. I would like to contribute

**Comment by sarkartanmay393** [comment]
@abhijithp05 Sure! Go ahead. 

Remember to sign all of your commits by adding `-s` in all of your commits.

**Comment by abhijithp05** [comment]
> @abhijithp05 Sure! Go ahead.
> 
> Remember to sign all of your commits by adding `-s` in all of your commits.

Sure

**Comment by abhijithp05** [comment]
@sarkartanmay393 Please review and merge the PR

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 Please review and merge the PR

@abhijithp05 I reviewed! It's good.
