### ISSUE TITLE
Add: sticky `Back to top` button on * pages

### ISSUE THREAD

**Issue by sarkartanmay393** [sarkartanmay393/Portfolio-V2#2]
Whenever one scrolls down on any page, there should be a visible `back-to-top`  button.

**Comment by ThePiyushAggarwal** [comment]
Hi Tanmay!
I would like to solve this issue over the weekend.
Can you please assign this to me?

**Comment by sarkartanmay393** [comment]
@ThePiyushAggarwal It's all yours!

**Comment by ThePiyushAggarwal** [comment]
Raised a PR for this issue #6
