### ISSUE TITLE
Fix: Redesign Project Cards 📇

### ISSUE THREAD

**Issue by sarkartanmay393** [sarkartanmay393/Portfolio-V2#3]
Here, the project description area doesn't look minimal. Whole card should be minimal, elegant and stable to look at.

![image](https://user-images.githubusercontent.com/84321236/215124050-4f13028b-6e11-4623-9e72-eaa6e269eed7.png)

**Comment by codecdekamal** [comment]
Hello, I am kamal and I want to contribute in open source.
[https://github.com/codecdekamal](url)
